export interface Country {
  iso: string    // ISO 3166-1 alpha-2, lowercase
  en: string
  zh: string
}

export const COUNTRIES: Country[] = [
  { iso: 'af', en: 'Afghanistan',           zh: '阿富汗' },
  { iso: 'al', en: 'Albania',               zh: '阿爾巴尼亞' },
  { iso: 'dz', en: 'Algeria',               zh: '阿爾及利亞' },
  { iso: 'ad', en: 'Andorra',               zh: '安道爾' },
  { iso: 'ao', en: 'Angola',               zh: '安哥拉' },
  { iso: 'ag', en: 'Antigua and Barbuda',   zh: '安地卡及巴布達' },
  { iso: 'ar', en: 'Argentina',             zh: '阿根廷' },
  { iso: 'am', en: 'Armenia',               zh: '亞美尼亞' },
  { iso: 'au', en: 'Australia',             zh: '澳洲' },
  { iso: 'at', en: 'Austria',               zh: '奧地利' },
  { iso: 'az', en: 'Azerbaijan',            zh: '亞塞拜然' },
  { iso: 'bs', en: 'Bahamas',               zh: '巴哈馬' },
  { iso: 'bh', en: 'Bahrain',               zh: '巴林' },
  { iso: 'bd', en: 'Bangladesh',            zh: '孟加拉' },
  { iso: 'by', en: 'Belarus',               zh: '白俄羅斯' },
  { iso: 'be', en: 'Belgium',               zh: '比利時' },
  { iso: 'bz', en: 'Belize',               zh: '貝里斯' },
  { iso: 'bj', en: 'Benin',                zh: '貝南' },
  { iso: 'bt', en: 'Bhutan',               zh: '不丹' },
  { iso: 'bo', en: 'Bolivia',              zh: '玻利維亞' },
  { iso: 'ba', en: 'Bosnia and Herzegovina',zh: '波士尼亞與赫塞哥維納' },
  { iso: 'bw', en: 'Botswana',             zh: '波札那' },
  { iso: 'br', en: 'Brazil',               zh: '巴西' },
  { iso: 'bn', en: 'Brunei',               zh: '汶萊' },
  { iso: 'bg', en: 'Bulgaria',             zh: '保加利亞' },
  { iso: 'bf', en: 'Burkina Faso',         zh: '布吉納法索' },
  { iso: 'bi', en: 'Burundi',              zh: '蒲隆地' },
  { iso: 'cv', en: 'Cabo Verde',           zh: '維德角' },
  { iso: 'kh', en: 'Cambodia',             zh: '柬埔寨' },
  { iso: 'cm', en: 'Cameroon',             zh: '喀麥隆' },
  { iso: 'ca', en: 'Canada',               zh: '加拿大' },
  { iso: 'cf', en: 'Central African Republic', zh: '中非' },
  { iso: 'td', en: 'Chad',                 zh: '查德' },
  { iso: 'cl', en: 'Chile',                zh: '智利' },
  { iso: 'cn', en: 'China',                zh: '中國' },
  { iso: 'co', en: 'Colombia',             zh: '哥倫比亞' },
  { iso: 'km', en: 'Comoros',              zh: '科摩羅' },
  { iso: 'cd', en: 'Congo (DRC)',          zh: '剛果（民主共和國）' },
  { iso: 'cg', en: 'Congo (Republic)',     zh: '剛果（共和國）' },
  { iso: 'cr', en: 'Costa Rica',           zh: '哥斯大黎加' },
  { iso: 'ci', en: "Côte d'Ivoire",        zh: '象牙海岸' },
  { iso: 'hr', en: 'Croatia',              zh: '克羅埃西亞' },
  { iso: 'cu', en: 'Cuba',                 zh: '古巴' },
  { iso: 'cy', en: 'Cyprus',               zh: '賽普勒斯' },
  { iso: 'cz', en: 'Czech Republic',       zh: '捷克' },
  { iso: 'dk', en: 'Denmark',              zh: '丹麥' },
  { iso: 'dj', en: 'Djibouti',            zh: '吉布地' },
  { iso: 'dm', en: 'Dominica',             zh: '多米尼克' },
  { iso: 'do', en: 'Dominican Republic',   zh: '多明尼加' },
  { iso: 'ec', en: 'Ecuador',              zh: '厄瓜多' },
  { iso: 'eg', en: 'Egypt',                zh: '埃及' },
  { iso: 'sv', en: 'El Salvador',          zh: '薩爾瓦多' },
  { iso: 'gq', en: 'Equatorial Guinea',    zh: '赤道幾內亞' },
  { iso: 'er', en: 'Eritrea',              zh: '厄利垂亞' },
  { iso: 'ee', en: 'Estonia',              zh: '愛沙尼亞' },
  { iso: 'sz', en: 'Eswatini',             zh: '史瓦帝尼' },
  { iso: 'et', en: 'Ethiopia',             zh: '衣索比亞' },
  { iso: 'fj', en: 'Fiji',                 zh: '斐濟' },
  { iso: 'fi', en: 'Finland',              zh: '芬蘭' },
  { iso: 'fr', en: 'France',               zh: '法國' },
  { iso: 'ga', en: 'Gabon',               zh: '加彭' },
  { iso: 'gm', en: 'Gambia',              zh: '甘比亞' },
  { iso: 'ge', en: 'Georgia',             zh: '喬治亞' },
  { iso: 'de', en: 'Germany',             zh: '德國' },
  { iso: 'gh', en: 'Ghana',               zh: '迦納' },
  { iso: 'gr', en: 'Greece',              zh: '希臘' },
  { iso: 'gd', en: 'Grenada',             zh: '格瑞那達' },
  { iso: 'gt', en: 'Guatemala',           zh: '瓜地馬拉' },
  { iso: 'gn', en: 'Guinea',              zh: '幾內亞' },
  { iso: 'gw', en: 'Guinea-Bissau',       zh: '幾內亞比索' },
  { iso: 'gy', en: 'Guyana',              zh: '蓋亞那' },
  { iso: 'ht', en: 'Haiti',               zh: '海地' },
  { iso: 'hn', en: 'Honduras',            zh: '宏都拉斯' },
  { iso: 'hk', en: 'Hong Kong',           zh: '香港' },
  { iso: 'hu', en: 'Hungary',             zh: '匈牙利' },
  { iso: 'is', en: 'Iceland',             zh: '冰島' },
  { iso: 'in', en: 'India',               zh: '印度' },
  { iso: 'id', en: 'Indonesia',           zh: '印尼' },
  { iso: 'ir', en: 'Iran',                zh: '伊朗' },
  { iso: 'iq', en: 'Iraq',                zh: '伊拉克' },
  { iso: 'ie', en: 'Ireland',             zh: '愛爾蘭' },
  { iso: 'il', en: 'Israel',              zh: '以色列' },
  { iso: 'it', en: 'Italy',               zh: '義大利' },
  { iso: 'jm', en: 'Jamaica',             zh: '牙買加' },
  { iso: 'jp', en: 'Japan',               zh: '日本' },
  { iso: 'jo', en: 'Jordan',              zh: '約旦' },
  { iso: 'kz', en: 'Kazakhstan',          zh: '哈薩克' },
  { iso: 'ke', en: 'Kenya',               zh: '肯亞' },
  { iso: 'ki', en: 'Kiribati',            zh: '吉里巴斯' },
  { iso: 'kw', en: 'Kuwait',              zh: '科威特' },
  { iso: 'kg', en: 'Kyrgyzstan',          zh: '吉爾吉斯' },
  { iso: 'la', en: 'Laos',               zh: '寮國' },
  { iso: 'lv', en: 'Latvia',             zh: '拉脫維亞' },
  { iso: 'lb', en: 'Lebanon',            zh: '黎巴嫩' },
  { iso: 'ls', en: 'Lesotho',            zh: '賴索托' },
  { iso: 'lr', en: 'Liberia',            zh: '賴比瑞亞' },
  { iso: 'ly', en: 'Libya',              zh: '利比亞' },
  { iso: 'li', en: 'Liechtenstein',      zh: '列支敦斯登' },
  { iso: 'lt', en: 'Lithuania',          zh: '立陶宛' },
  { iso: 'lu', en: 'Luxembourg',         zh: '盧森堡' },
  { iso: 'mo', en: 'Macao',              zh: '澳門' },
  { iso: 'mg', en: 'Madagascar',         zh: '馬達加斯加' },
  { iso: 'mw', en: 'Malawi',            zh: '馬拉威' },
  { iso: 'my', en: 'Malaysia',           zh: '馬來西亞' },
  { iso: 'mv', en: 'Maldives',           zh: '馬爾地夫' },
  { iso: 'ml', en: 'Mali',              zh: '馬利' },
  { iso: 'mt', en: 'Malta',             zh: '馬爾他' },
  { iso: 'mh', en: 'Marshall Islands',  zh: '馬紹爾群島' },
  { iso: 'mr', en: 'Mauritania',        zh: '茅利塔尼亞' },
  { iso: 'mu', en: 'Mauritius',         zh: '模里西斯' },
  { iso: 'mx', en: 'Mexico',            zh: '墨西哥' },
  { iso: 'fm', en: 'Micronesia',        zh: '密克羅尼西亞' },
  { iso: 'md', en: 'Moldova',           zh: '摩爾多瓦' },
  { iso: 'mc', en: 'Monaco',            zh: '摩納哥' },
  { iso: 'mn', en: 'Mongolia',          zh: '蒙古' },
  { iso: 'me', en: 'Montenegro',        zh: '蒙特內哥羅' },
  { iso: 'ma', en: 'Morocco',           zh: '摩洛哥' },
  { iso: 'mz', en: 'Mozambique',        zh: '莫三比克' },
  { iso: 'mm', en: 'Myanmar',           zh: '緬甸' },
  { iso: 'na', en: 'Namibia',           zh: '納米比亞' },
  { iso: 'nr', en: 'Nauru',             zh: '諾魯' },
  { iso: 'np', en: 'Nepal',             zh: '尼泊爾' },
  { iso: 'nl', en: 'Netherlands',       zh: '荷蘭' },
  { iso: 'nz', en: 'New Zealand',       zh: '紐西蘭' },
  { iso: 'ni', en: 'Nicaragua',         zh: '尼加拉瓜' },
  { iso: 'ne', en: 'Niger',             zh: '尼日' },
  { iso: 'ng', en: 'Nigeria',           zh: '奈及利亞' },
  { iso: 'mk', en: 'North Macedonia',   zh: '北馬其頓' },
  { iso: 'no', en: 'Norway',            zh: '挪威' },
  { iso: 'om', en: 'Oman',              zh: '阿曼' },
  { iso: 'pk', en: 'Pakistan',          zh: '巴基斯坦' },
  { iso: 'pw', en: 'Palau',            zh: '帛琉' },
  { iso: 'pa', en: 'Panama',           zh: '巴拿馬' },
  { iso: 'pg', en: 'Papua New Guinea',  zh: '巴布亞新幾內亞' },
  { iso: 'py', en: 'Paraguay',         zh: '巴拉圭' },
  { iso: 'pe', en: 'Peru',             zh: '秘魯' },
  { iso: 'ph', en: 'Philippines',       zh: '菲律賓' },
  { iso: 'pl', en: 'Poland',           zh: '波蘭' },
  { iso: 'pt', en: 'Portugal',         zh: '葡萄牙' },
  { iso: 'qa', en: 'Qatar',            zh: '卡達' },
  { iso: 'ro', en: 'Romania',          zh: '羅馬尼亞' },
  { iso: 'ru', en: 'Russia',           zh: '俄羅斯' },
  { iso: 'rw', en: 'Rwanda',           zh: '盧安達' },
  { iso: 'kn', en: 'Saint Kitts and Nevis', zh: '聖克里斯多福及尼維斯' },
  { iso: 'lc', en: 'Saint Lucia',      zh: '聖露西亞' },
  { iso: 'vc', en: 'Saint Vincent and the Grenadines', zh: '聖文森及格瑞那丁' },
  { iso: 'ws', en: 'Samoa',            zh: '薩摩亞' },
  { iso: 'sm', en: 'San Marino',       zh: '聖馬利諾' },
  { iso: 'st', en: 'São Tomé and Príncipe', zh: '聖多美普林西比' },
  { iso: 'sa', en: 'Saudi Arabia',     zh: '沙烏地阿拉伯' },
  { iso: 'sn', en: 'Senegal',          zh: '塞內加爾' },
  { iso: 'rs', en: 'Serbia',           zh: '塞爾維亞' },
  { iso: 'sc', en: 'Seychelles',       zh: '塞席爾' },
  { iso: 'sl', en: 'Sierra Leone',     zh: '獅子山' },
  { iso: 'sg', en: 'Singapore',        zh: '新加坡' },
  { iso: 'sk', en: 'Slovakia',         zh: '斯洛伐克' },
  { iso: 'si', en: 'Slovenia',         zh: '斯洛維尼亞' },
  { iso: 'sb', en: 'Solomon Islands',  zh: '索羅門群島' },
  { iso: 'so', en: 'Somalia',          zh: '索馬利亞' },
  { iso: 'za', en: 'South Africa',     zh: '南非' },
  { iso: 'ss', en: 'South Sudan',      zh: '南蘇丹' },
  { iso: 'es', en: 'Spain',            zh: '西班牙' },
  { iso: 'lk', en: 'Sri Lanka',        zh: '斯里蘭卡' },
  { iso: 'sd', en: 'Sudan',            zh: '蘇丹' },
  { iso: 'sr', en: 'Suriname',         zh: '蘇利南' },
  { iso: 'se', en: 'Sweden',           zh: '瑞典' },
  { iso: 'ch', en: 'Switzerland',      zh: '瑞士' },
  { iso: 'sy', en: 'Syria',            zh: '敘利亞' },
  { iso: 'tw', en: 'Taiwan',           zh: '台灣' },
  { iso: 'tj', en: 'Tajikistan',       zh: '塔吉克' },
  { iso: 'tz', en: 'Tanzania',         zh: '坦尚尼亞' },
  { iso: 'th', en: 'Thailand',         zh: '泰國' },
  { iso: 'tl', en: 'Timor-Leste',     zh: '東帝汶' },
  { iso: 'tg', en: 'Togo',            zh: '多哥' },
  { iso: 'to', en: 'Tonga',           zh: '東加' },
  { iso: 'tt', en: 'Trinidad and Tobago', zh: '千里達及托巴哥' },
  { iso: 'tn', en: 'Tunisia',          zh: '突尼西亞' },
  { iso: 'tr', en: 'Turkey',           zh: '土耳其' },
  { iso: 'tm', en: 'Turkmenistan',     zh: '土庫曼' },
  { iso: 'tv', en: 'Tuvalu',          zh: '吐瓦魯' },
  { iso: 'ug', en: 'Uganda',          zh: '烏干達' },
  { iso: 'ua', en: 'Ukraine',         zh: '烏克蘭' },
  { iso: 'ae', en: 'United Arab Emirates', zh: '阿聯酋' },
  { iso: 'gb', en: 'United Kingdom',  zh: '英國' },
  { iso: 'us', en: 'United States',   zh: '美國' },
  { iso: 'uy', en: 'Uruguay',         zh: '烏拉圭' },
  { iso: 'uz', en: 'Uzbekistan',      zh: '烏茲別克' },
  { iso: 'vu', en: 'Vanuatu',        zh: '萬那杜' },
  { iso: 've', en: 'Venezuela',       zh: '委內瑞拉' },
  { iso: 'vn', en: 'Vietnam',         zh: '越南' },
  { iso: 'ye', en: 'Yemen',           zh: '葉門' },
  { iso: 'zm', en: 'Zambia',         zh: '尚比亞' },
  { iso: 'zw', en: 'Zimbabwe',        zh: '辛巴威' },
]

export function flagUrl(iso: string) {
  return `https://flagcdn.com/w40/${iso.toLowerCase()}.png`
}

export function groupByLetter(countries: Country[]): Map<string, Country[]> {
  const map = new Map<string, Country[]>()
  for (const c of countries) {
    const letter = c.en[0].toUpperCase()
    if (!map.has(letter)) map.set(letter, [])
    map.get(letter)!.push(c)
  }
  return map
}
